name: smerp_go
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.7+04

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  date_time_format: ^2.0.1
  connectivity_plus: ^6.1.4
  flutter_screenutil: ^5.6.1
  syncfusion_flutter_datepicker: ^29.1.38
  flutter_image: ^4.1.9
  smooth_page_indicator: ^1.2.1
  device_info_plus: ^11.3.0
  permission_handler: ^12.0.0+1
  mask_text_input_formatter: ^2.9.0
  truncate: ^3.0.1
  image_cropper: ^9.1.0
  pin_code_fields: ^8.0.1
  flutter_svg:
  pdf_widget_wrapper: ^1.0.4
  cupertino_icons: ^1.0.6
  animated_text_kit: ^4.2.2
  overlay_loader_with_app_icon: ^0.0.3
  flutter_masked_text2: ^0.9.1
  flutter_staggered_animations: ^1.1.1
  camera: ^0.10.5+5
  path_provider: ^2.1.0
  image_picker: ^1.0.2
  pdf: ^3.11.3
  flutter_pdfview: ^1.2.5
  share_plus: ^11.0.0
  url_launcher: ^6.1.11
  package_info_plus:
  buttons_tabbar: ^1.3.7+1
  shared_preferences:
  pull_to_refresh: ^2.0.0
  printing: ^5.10.4
  screenshot: ^3.0.0
  fluttertoast: ^8.2.4
  image_gallery_saver_plus: ^4.0.1
  syncfusion_flutter_barcodes: any
  lottie: ^3.2.0
  flutter_bloc:
  equatable:
  gap: ^3.0.1
  date_format: ^2.0.7
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  solar_icons: ^0.0.5
  firebase_remote_config: ^5.4.4
  firebase_core: ^3.13.1
  firebase_analytics: ^11.4.6
  http:
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1
  syncfusion_flutter_pdfviewer: ^29.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "androiddd"
  ios: true
  image_path: "assets/smerpgoLogo.svg"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/json/success.json
    - assets/good.svg
    - assets/notification.svg
    - assets/notification.png
    - assets/smerp_dev.png
    - assets/edit.svg
    - assets/delete.svg
    - assets/search.svg
    - assets/goodImg.png
    - assets/waaz.png
    - assets/smerpBgAnimation.gif
    - assets/smerp_heading.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: inter
      fonts:
        - asset: font/inter_regular.ttf
#        - asset: font/inter_light.ttf
#        - asset: font/inter_extraLight.ttf
#        - asset: font/inter_extraBold.ttf
#        - asset: font/inter_bold.ttf
#        - asset: font/inter_black.ttf
#        - asset: font/inter_medium.ttf
#        - asset: font/inter_semiBold.ttf

    - family: TomatoGrotesk
      fonts:
        - asset: font/TomatoGrotesk-Bold.otf
        - asset: font/TomatoGrotesk-Medium.otf
        - asset: font/TomatoGrotesk-Regular.otf
        - asset: font/TomatoGrotesk-SemiBold.otf

    - family: Graphik
      fonts:
        - asset: font/graphik_bold.ttf
        - asset: font/graphik_medium.ttf
        - asset: font/graphik_regular.ttf
        - asset: font/graphik_semibold.ttf
        - asset: font/graphik_light.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
