name: smerp_go
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.7+04

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get:
#  device_information: ^0.0.4
  date_time_format: ^2.0.1
  connectivity_plus: ^1.4.0
  flutter_screenutil: ^5.6.1
  syncfusion_flutter_datepicker: ^23.1.44
#  convert: ^3.0.1
  flutter_image:
  smooth_page_indicator:
  device_info_plus:
  permission_handler:
  mask_text_input_formatter:
#  csc_picker:
  truncate:
  image_cropper: ^5.0.0
#  flash:
#  flutter_easyloading:
  ots:
  pin_code_fields: ^8.0.1
  flutter_svg:
  pdf_widget_wrapper: ^1.0.4
#  flutter_animate:
  cupertino_icons:
  animated_text_kit: ^4.2.2
  overlay_loader_with_app_icon: ^0.0.3
#  intl: any
  flutter_masked_text2:
#  dropdown_button2: ^2.1.2
  flutter_staggered_animations:
#  contacts_service: ^0.6.3
  camera:
  path_provider:
#  path:
  image_picker: ^1.0.2
  pdf:
  flutter_pdfview: ^1.2.5
  share_plus: ^7.1.0
  url_launcher:
  package_info_plus:
  buttons_tabbar: ^1.3.7+1
  shared_preferences:
  pull_to_refresh: ^2.0.0
  printing:
  screenshot: ^2.2.0
  fluttertoast: ^8.0.8
  image_gallery_saver: ^2.0.3
  flutter_image_saver:
  syncfusion_flutter_barcodes: any
  lottie: ^2.5.0
  flutter_bloc:
  equatable:
  gap: ^3.0.1
  date_format: ^2.0.7
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  solar_icons: ^0.0.5
  firebase_remote_config: ^4.3.10
  firebase_core:
  firebase_analytics:
#  download: ^1.0.0
  http:
  firebase_messaging: ^14.7.19
  device_imei: ^0.0.1
  flutter_local_notifications:
#  mobile_device_identifier: ^0.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "androiddd"
  ios: true
  image_path: "assets/smerpgoLogo.svg"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/json/success.json
    - assets/good.svg
    - assets/notification.svg
    - assets/notification.png
    - assets/smerp_dev.png
    - assets/edit.svg
    - assets/delete.svg
    - assets/search.svg
    - assets/goodImg.png
    - assets/waaz.png
    - assets/smerpBgAnimation.gif
    - assets/smerp_heading.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: inter
      fonts:
        - asset: font/inter_regular.ttf
#        - asset: font/inter_light.ttf
#        - asset: font/inter_extraLight.ttf
#        - asset: font/inter_extraBold.ttf
#        - asset: font/inter_bold.ttf
#        - asset: font/inter_black.ttf
#        - asset: font/inter_medium.ttf
#        - asset: font/inter_semiBold.ttf

    - family: TomatoGrotesk
      fonts:
        - asset: font/TomatoGrotesk-Bold.otf
        - asset: font/TomatoGrotesk-Medium.otf
        - asset: font/TomatoGrotesk-Regular.otf
        - asset: font/TomatoGrotesk-SemiBold.otf

    - family: Graphik
      fonts:
        - asset: font/graphik_bold.ttf
        - asset: font/graphik_medium.ttf
        - asset: font/graphik_regular.ttf
        - asset: font/graphik_semibold.ttf
        - asset: font/graphik_light.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
