import 'package:get/get.dart';
import 'package:smerp_go/model/response/inventoryList.dart';
import 'package:smerp_go/model/response/report/performingAnalysis.dart';
import 'package:smerp_go/model/response/report/salesAnalysis.dart';
import 'package:smerp_go/model/response/sales/saleList.dart';
import 'package:smerp_go/model/response/salesList.dart';
import 'package:smerp_go/model/response/product/productList.dart'as collectionS;
import '../../model/response/catalogListResponse.dart';
import '../../model/response/getCollectionList.dart';
import '../../model/response/notificationList.dart';
import '../../model/response/order/allOrders.dart';
import '../../model/response/productCategory.dart';
import '../../model/response/report/productAnalysis.dart';
import '../app_services/helperClass.dart';

List<DefaultProductCategory> productCategoryList =[];
List<DefaultProductCategory> productUnitCategoryList =[];
List<InventoryInfo> inventoryListTemp =[];
List<collectionS.InventoryInfo> collectionInventoryListTemp =[];
List<CollectionList> collectionListTemp=[];
List<NotificationList> notificationListTemp=[];
List<SalesDatum> saleListTemp =RxList();
List<Orders> orderListTemp =RxList();
List<CatalogData> catalogListTemp =[];
List<CatalogFull> catalogsFTemp = [];
SalesAnalysisThisWeek? saleAnalysisThisWeek ;
SalesAnalysisThisWeek? saleAnalysisThisMonth ;
SalesAnalysisThisWeek? saleAnalysisLastMonth ;
SalesAnalysisThisWeek? saleAnalysisLastWeek ;
ProductAnalysis? productAnalysisThisWeek;
ProductAnalysis? productAnalysisLastWeek;
ProductAnalysis? productAnalysisThisMonth;
ProductAnalysis? productAnalysisLastMonth;
PerformingAnalysis? performingAnalysis;
RxBool isCreatedSale = false.obs;
RxBool isCreatedProduct = false.obs;
RxBool isFirstTimeReport= true.obs;